version: "1.0"

base_image_repo: docker.io/msg555/tplbuild-base
stage_image_name: '{{ stage_name }}'
stage_push_name: |
  docker.io/msg555/{{ stage_name }}
  {%- if profile != "release" -%}
    -{{ profile }}
  {%- endif -%}
  {%- if vars.tag is defined -%}
    :{{ vars.tag }}
  {%- endif -%}

dockerfile_syntax: 
  docker/dockerfile:1.4

platforms:
  - linux/amd64
  - linux/arm64

default_profile: dev
profiles:
  dev:
    env: dev
    python_version: '3.8'
  dev_3_9:
    env: dev
    python_version: '3.9'
  dev_3_10:
    env: dev
    python_version: '3.10'
  release:
    env: release
    python_version: '3.8'

stages:
  tplbuild:
    image_names: [abc, def]

contexts:
  default:
    ignore: | # Set 
      *
      !tplbuild
      !requirements*
