name: tplbuild
on:
  push:
    branches:
      - main
jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Lint
      run: make docker-lint
    - name: Test
      run: make docker-test

  check-base:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Check Base
      run: |
        ./bootstrap.sh base-build --check

  build-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      env:
        DOCKER_REGISTRY_USERNAME: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
        DOCKER_REGISTRY_PASSWORD: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
      run: |
        docker login -u "${DOCKER_REGISTRY_USERNAME}" -p "${DOCKER_REGISTRY_PASSWORD}"
        ./bootstrap.sh publish --profile release
