name: tplbuild
on:
  push:
    branches:
      - main
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Lint
      run: make docker-lint

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        profile: [dev, dev_3_9, dev_3_10, dev_3_11, dev_3_12]
    steps:
    - uses: actions/checkout@v2
    - name: Test ${{ matrix.profile }}
      env:
        PROFILE: ${{ matrix.profile }}
      run: make docker-test

  check-base:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Check Base
      run: |
        ./bootstrap.sh base-build --check

  build-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up QEMU
      uses: docker/setup-qemu-action@master
      with:
        platforms: all
    - name: Build
      env:
        DOCKER_REGISTRY_USERNAME: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
        DOCKER_REGISTRY_PASSWORD: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
      run: |
        docker login -u "${DOCKER_REGISTRY_USERNAME}" -p "${DOCKER_REGISTRY_PASSWORD}"
        ./bootstrap.sh publish --profile release
